from .components.gelatin_box.gelatin_box import *
from .components.potted_meat_can.potted_meat_can import *
from .components.power_drill.power_drill import *
from .components.pudding_box.pudding_box import *
from .components.tuna_fish_can.tuna_fish_can import *
from .components.mustard_bottle.mustard_bottle import *
from .components.tomato_soup_can.tomato_soup_can import *
from .components.cracker_box.cracker_box import *
from .components.master_chef_can.master_chef_can import *