from mjcomponent.scene import BasicScene
from mjcomponent.env import *

env = BasicScene()
power_drill = Power_drill()
potted_meat_can =Potted_meat_can()
gelatin_box = Gelatin_box()
pudding_box = Pudding_box()
tuna_fish_can = Tuna_fish_can()
mustard_bottle = Mustard_bottle()
tomato_soup_can = Tomato_soup_can()
# cracker_box = Cracker_box()
# master_chef_can = Master_chef_can()
# sugar_box =  Sugar_box()
# banana = Banana()
# strawberry = Strawberry()
apple = Apple()
lemon = Lemon()
peach = Peach()
# pear = Pear()
# orange = Orange()
# plum = Plum()
# plate = Plate()
# pitcher_base = Pitcher_base()
# bleach_cleanser = Bleach_cleanser()
# bowl = Bowl()
# mug = Mug()
# sponge = Sponge()
# spoon = Spoon()
# fork = Fork()
# knife = Knife()
# spatula = Spatula()
# wood_block = Wood_block()
# scssors = Scissors()
padlock = Padlock()
large_marker = Large_marker()
env.attach_objects(power_drill.mjcf_root)
env.attach_objects(potted_meat_can.mjcf_root,[0.2,0,0])
env.attach_objects(gelatin_box.mjcf_root,[0.4,0,0])
env.attach_objects(pudding_box.mjcf_root,[0,-0.2,0])
env.attach_objects(tuna_fish_can.mjcf_root,[0,-0.4,0])
env.attach_objects(mustard_bottle.mjcf_root,[0,0.2,0])
env.attach_objects(tomato_soup_can.mjcf_root,[0,0.4,0])
# env.attach_objects(master_chef_can.mjcf_root,[0,0.6,0])
# env.attach_objects(cracker_box.mjcf_root,[0,-0.6,0])
# env.attach_objects(sugar_box.mjcf_root,[0,-0.8,0.1])
# env.attach_objects(banana.mjcf_root,[0,-1,0.1])
# env.attach_objects(strawberry.mjcf_root,[0,-1.2,0])
env.attach_objects(apple.mjcf_root,[0,-1.4,0])
env.attach_objects(lemon.mjcf_root,[0.6,0,0])
env.attach_objects(peach.mjcf_root,[0.8,0,0])
# env.attach_objects(pear.mjcf_root,[0.2,-0.2,0])
# env.attach_objects(orange.mjcf_root,[0.2,-0.4,0])
# env.attach_objects(plum.mjcf_root,[0.2,-0.6,0])
# env.attach_objects(pitcher_base.mjcf_root,[0.2,-0.8,0])
# env.attach_objects(bleach_cleanser.mjcf_root,[0.2,-1,0])
# env.attach_objects(bowl.mjcf_root,[0.2,-1.2,0])
# env.attach_objects(mug.mjcf_root,[0.2,-1.4,0])
# env.attach_objects(sponge.mjcf_root,[0.2,-1.6,0])
# env.attach_objects(plate.mjcf_root,[0.4,-0.2,0])
# env.attach_objects(fork.mjcf_root,[0.6,-0.2,0])
# env.attach_objects(spoon.mjcf_root,[0.6,-0.4,0])
# env.attach_objects(knife.mjcf_root,[0.6,-0.6,0])
# env.attach_objects(spatula.mjcf_root,[0.6,-0.8,0])
# env.attach_objects(wood_block.mjcf_root,[0.6,-1,0])
# env.attach_objects(scssors.mjcf_root,[0.6,-1.2,0])
env.attach_objects(padlock.mjcf_root,[0.4,-0.4,0])
env.attach_objects(large_marker.mjcf_root,[0.4,-0.6,0])
env.initialize()
while True:
    env.step_simulation()
